puts "The students on my cohort at Makers Academy"
puts "---------------"
puts "Asta"
puts "G"
puts "Hannah"
puts "Simon"
puts "Chris"
puts "Erica"
puts "Kennedy"
puts "Annette"
puts "Lara"
puts "James"
puts "Jeremy"
puts "Giacomo"
puts "Nisar"
puts "Bruce"